# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_location', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('mgmt_IP', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('data_IP_1', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('data_IP_2', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('bmc_IP', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Owner')),
            ],
        ),
    ]
