# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_location', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=64, unique=True)),
                ('server_mgmt_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('server_data1_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('server_data2_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('server_owner', models.CharField(max_length=64)),
                ('server_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Location')),
            ],
        ),
    ]
