# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='server_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Owner'),
        ),
    ]
