# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20170412_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server_data1_ip',
            new_name='data_IP_1',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_data2_ip',
            new_name='data_IP_2',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_mgmt_ip',
            new_name='mgmt_IP',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_owner',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='server',
            name='bmc_IP',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
