# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
