# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20170718_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(max_length=255, upload_to='media/'),
        ),
    ]
