# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20170719_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='csv/')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
