# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20170727_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='file',
            field=models.FileField(max_length=255, upload_to='csv/import/'),
        ),
    ]
