# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20170727_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_address', models.GenericIPAddressField(default='', unique=True)),
                ('dns_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Location')),
            ],
        ),
    ]
