# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_dns'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntp_address', models.GenericIPAddressField(default='', unique=True)),
                ('ntp_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Location')),
            ],
        ),
    ]
