# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_ntp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(default='', unique=True)),
                ('vlan', models.CharField(blank=True, max_length=64, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Location')),
            ],
        ),
    ]
